# version: 2

# models:
#   - name: my_first_model
#     description: "A starter dbt model"
#     columns:
#       - name: id
#         description: "The primary key for this table"
#         tests:
#           - unique
#           - not_null
#       - name: created_at
#         description: "Timestamp when the record was created"
#         tests:
#           - not_null

#   - name: my_second_model
#     description: "A downstream model that depends on my_first_model"
#     columns:
#       - name: user_id
#         description: "Foreign key reference to users table"
#         tests:
#           - relationships:
#               to: ref('users')
#               field: id
#       - name: amount
#         description: "Transaction amount"
#         tests:
#           - not_null
#           - positive_values

# sources:
#   - name: raw_data
#     database: raw_db
#     schema: public
#     tables:
#       - name: customers
#         columns:
#           - name: customer_id
#             tests:
#               - unique
#               - not_null
#       - name: orders
#         loaded_at_field: created_at
#         freshness:
#           warn_after: {count: 12, period: hour}
#           error_after: {count: 24, period: hour}

